name: test-build
on:
  pull_request:
  push:

concurrency:
  group: "${{ github.ref }}"
  cancel-in-progress: true
jobs:
  build-debian:
    strategy:
      # Keep other matrix jobs running, even if one fails.
      fail-fast: false
      matrix:
        host_release:
          - unstable

    # We want a working shell, qemu, python and docker. Specific version should not matter (much).
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: ./test/gha-build-deb.sh
        name: "Build .deb for ${{matrix.host_release}}"
        env:
          HOST_RELEASE: ${{matrix.host_release}}

      - name: Archive built .deb
        uses: actions/upload-artifact@v4
        with:
          name: deb-${{matrix.host_release}}
          if-no-files-found: error
          path: |
            *.deb
